#!/bin/sh

if [ "latest" = "$DOCKER_TAG" ] && [ "master" = "$SOURCE_BRANCH" ]; then
    MARKDOWNLINT_CLI_VER=$(curl https://registry.npmjs.org/markdownlint-cli -sLo- | grep -Po '"latest":"\d+\.\d+\.\d+"' | awk -F'"' '{print $4}')
else
    MARKDOWNLINT_CLI_VER="$SOURCE_BRANCH"
fi

docker build --build-arg MARKDOWNLINT_CLI_VER="$MARKDOWNLINT_CLI_VER" -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
